version: '3.7'
services:
  db:
    image: postgres:11.1
    container_name: "radius-on-rails-db"
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - PGHOST=db
      - PGUSER=postgres
    volumes:
      - .:/radius-on-rails
    ports:
      - "3000:3000"
    depends_on:
      - db